### ISSUE TITLE
Dockerfile or docker container

### ISSUE THREAD

**Issue by mahmut-gundogdu** [swiperproxy/swiperproxy#30]
hi. i need docker file or container is it possible? any one has it?

**Comment by Techwolf12** [comment]
We currrently don't have one but it should be really easy to make, do you have experience with creating containers? We accept pull requests

**Comment by mahmut-gundogdu** [comment]
actually i tried. i took a error 
"Traceback (most recent call last):
  File "Proxy.py", line 927, in <module>
    p = Proxy(c)
  File "Proxy.py", line 761, in __init__
    server_side=True)
  File "/usr/lib/python2.7/ssl.py", line 891, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 509, in __init__
    self._context.load_cert_chain(certfile, keyfile)
IOError: [Errno 2] No such file or directory"

**Comment by Techwolf12** [comment]
I can be wrong but is it missing it's SSL Certificate? https://swiperproxy.github.io/documentation/sys-genx509.html

**Comment by mahmut-gundogdu** [comment]
i tried it. i tripped on this step
"$ cat /etc/ssl/certs/ca.intermediate.cert.pem >> /opt/SwiperProxy/swiperproxy/certificate.pem"
there is no ca.intermediate.cert.pem.
i skipped but error still active.

**Comment by fopina** [comment]
#33 PR for docker builds!
