### ISSUE TITLE
Error after installing / ImportError: libstreamhtmlparser.so.0

### ISSUE THREAD

**Issue by bllim** [swiperproxy/swiperproxy#31]
Hi, thanks for great web proxy script. I wanted to give it a try, but i couldn't. I downloaded and tried to install as mentioned in documents. I installed requirements. I also built and installed streamhtmlparser in the include directory. These steps is passed without any error. But at last, when I tried to run, I got following error:

```
Traceback (most recent call last):
  File "Proxy.py", line 38, in <module>
    from Page import Page
  File "/opt/SwiperProxy/swiperproxy/Page.py", line 23, in <module>
    from streamhtmlparser import *
ImportError: libstreamhtmlparser.so.0: cannot open shared object file: No such file or directory
```

I should say, I am a little bit new at python. So I may miss something obvious. If so, sorry for taking time. Thanks.

**Comment by Mr4x3** [comment]
same issue

**Comment by Techwolf12** [comment]
Sorry, the project is not really maintained anymore and I am currently not at home. I will try to compile it when I am back from my holiday and see what the issue is. Something probably changed with libstreamhtmlparser, a workaround might be to pick a version from a year ago?

**Comment by Mr4x3** [comment]
can you please tell maybe version of it

**Comment by Mr4x3** [comment]
tried v1.0 dont work

**Comment by Techwolf12** [comment]
I don't know yet, sorry. I will try it out somewhere this week

**Comment by Techwolf12** [comment]
Copy the Python packages to a location where Debian will recognize them:
$ cp /usr/local/lib/python2.7/dist-packages/* /usr/lib/python2.7/dist-packages
$ ldconfig -v

Did you try that? What python version do you run? 2 or 3?

**Comment by Mr4x3** [comment]
Iam using python2 and i have tried that and that did not fix it.

**Comment by Mr4x3** [comment]
Cant we make like a pip package for this library atleast for debian based systems

**Comment by vaibhavgeek** [comment]
Any updates? Even I am facing the same issue.

**Comment by n1try** [comment]
Same problem here...

**Comment by paulborile** [comment]
Same here
